# Generated by Django 5.2.17 on 2026-09-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_product_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
